In [28]:
import tensorflow as tf

In [29]:
t1 = tf.constant([[1, 2], 
                 [3, 4], 
                 [5, 6]])

In [30]:
tf.random.shuffle(t1, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [31]:
t2 = tf.constant([[11, 12], 
                 [13, 14], 
                 [15, 16]])

In [33]:
tf.random.set_seed(42)
tf.random.shuffle(t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 14],
       [15, 16],
       [11, 12]], dtype=int32)>

## Other ways to create a tensor

In [38]:
tf.ones([1, 2, 3, 4])

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [42]:
tf.zeros(shape=(1, 2, 3, 4))

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
# NumPy arrays into tensors

In [45]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

In [48]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [55]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A, shape=(3, 8))

In [56]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [57]:
B

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>