## Introduction to the course
* Introduction to the tensors
* Getting information from tensors
* Manupulating tensors
* Tensors and numpy
* Using @tf.function
* Using GPUs with tensorflow

## Constants

In [328]:
import tensorflow as tf
import tensorflow_probability as tfp

In [139]:
print(tf.__version__)

2.4.1


In [140]:
# Creating the first tensor
scalar = tf.constant(7)

In [141]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [142]:
# numebr of dimensions of the tensor
scalar.ndim

0

In [143]:
# Creating a vector
vector = tf.constant([1, 2])

In [144]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [145]:
# Checking the dimension of the vector
vector.ndim

1

In [146]:
matrix = tf.constant([[10, 7],
                    [7, 10]])

In [147]:
matrix.ndim

2

In [148]:
# create another matrix
a_matrix = tf.constant([[1., 2.],
                       [3., 4.],
                       [5., 6.]], dtype=tf.float16)

In [149]:
a_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [150]:
a_matrix.ndim

2

In [151]:
tensor = tf.constant([[[1, 2, 3],[4, 5, 6]],
                     [[7, 8, 9], [10 ,11, 12]],
                     [[13, 14, 15], [16, 17, 18]]])

In [152]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [153]:
tensor.ndim

3

## Variables

 We will create the same tensors as above

In [154]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [155]:
changable_tensor = tf.Variable([10, 5]) # Variable
unchangable_tensor = tf.constant([1, 2]) # Constant 

In [156]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5], dtype=int32)>

In [157]:
unchangable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [158]:
changable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Can be assigned to something else
changable_tensor[0].assign(7)

In [ ]:
# Now lets try to change our unchangable vector
unchangable_tensor[0].assign(7)

## Creating random tensors

Random tensors that contain arbitary values

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

In [ ]:
random_1

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [ ]:
random_2

In [ ]:
random_1 == random_2

Shuffle
* To help in training else the model will get used to it, helps in shuffle the data

In [ ]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                           [5, 6]])

In [ ]:
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
# Converting numpy arrays into tensors

In [ ]:
import numpy as np

In [ ]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_B = np.arange(1, 25, dtype=np.int32)

In [ ]:
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))

In [ ]:
A

In [ ]:
numpy_B

In [ ]:
B = tf.constant(numpy_B, shape=(3, 8))

In [ ]:
B

### Getting informationg from tensors

* Shape
* Rank
* Axis or Dimension
* Size

In [196]:
A = tf.zeros([2, 3, 4, 5])

In [197]:
A

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [198]:
A.shape

TensorShape([2, 3, 4, 5])

In [199]:
A.ndim

4

In [200]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [201]:
print("datatype: ", A.dtype)
print("the dimensions (rank): ", A.ndim)
print("Shape of the tensor: ", A.shape)
print("Elements along the 0 axis: ", A.shape[0])
print("Elements along the last axis: ", A.shape[-1])
print("Total number of elemnents in out tensor: ", tf.size(A).numpy())

datatype:  <dtype: 'float32'>
the dimensions (rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elemnents in out tensor:  120


### Indexing the tensors

In [202]:
A[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [203]:
A[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [210]:
B = tf.constant([[10, 7],
                [3, 4]])

In [211]:
B.ndim, B.shape

(2, TensorShape([2, 2]))

In [212]:
B[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [213]:
# Adding the extra dimension
C = B[..., tf.newaxis]

In [214]:
C

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [215]:
# Expand the last axis
tf.expand_dims(B, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [217]:
# Expand the first axis
tf.expand_dims(B, axis=0) 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manupulating tensors (tensor operations)

In [226]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [227]:
# This is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [230]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [231]:
# Tensor multiplication - 1
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [232]:
# Tensor multiplication - 2
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

### Matrix multiplication

In machine learning, matrix multiplication is one of the commmon tensor operations

http://matrixmultiplication.xyz/ - Visulaize the same operations

In [235]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [236]:
# Legal matrix multiplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [241]:
# Scalar multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [237]:
mat_1 = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])

In [238]:
mat_2 = tf.constant([[3, 5], [6, 7], [1, 8]])

In [240]:
tf.matmul(mat_1, mat_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [243]:
# # This is to show that scalar doesn't work in all cases
mat_1 * mat_2

In [244]:
# Pythonic way to multiply 2 matrices
mat_1 @ mat_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [249]:
# Lets the change the shape of Y
mat_2_rs = tf.reshape(mat_2, shape=(2, 3))

In [250]:
tf.matmul(mat_2_rs, mat_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[56, 34, 38],
       [38, 40, 60]], dtype=int32)>

- Performing the dot product, using tensor dot
- Practising of transpose

In [257]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9 ,10], [11, 12]])

In [258]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [262]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [264]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

`tf.tensordot` and `tf.matmul` are the same, they perform the same operations

In [267]:
# Now let us do the matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [269]:
# Performing matrix multiplication b/w X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [274]:
# Viewing all the data of Y
Y, tf.reshape(Y, shape=(2, 3)), tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

Generally, when are working with matrix multiplication and one of the tensors axes doesn't line up, we should try to transpose it before performing the operation. Which would help do the matrix multiplication

### Changing the datatype of the tensor

In [291]:
# Creating a new tensor (float 32)
B = tf.constant([1.2, 1.3])
B.dtype

tf.float32

In [292]:
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 1.3], dtype=float32)>

In [293]:
C = tf.constant([1, 3])
C.dtype

tf.int32

In [294]:
# Changing the dtype from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 1.3], dtype=float16)>

In [295]:
# Changing from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 3.], dtype=float32)>

In [296]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 3.], dtype=float16)>

### Aggregating tensors

Condensing them from multiple values down to a smaller amount of values.

In [298]:
# Getting the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [299]:
# Getting the absolute value of the tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Form of aggregating
* Getting the min
* Getting the max
* Getting the mean of a tensor
* Getting the max of the tensor


In [318]:
# Creating a randome tensor
E = tf.constant(np.random.randint(0, 100, size=50))
E = tf.cast(E, dtype=tf.float16)

In [319]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [320]:
# Finding the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=float16, numpy=0.0>

In [321]:
# Finding the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float16, numpy=94.0>

In [322]:
# Finding the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=float16, numpy=46.97>

In [323]:
# Finidng the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=float16, numpy=2348.0>

In [326]:
# Finding the standard deaviation
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float16, numpy=25.52>

In [329]:
# Finding the variance
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=651.0>

In [332]:
# variance form the regular method
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=651.0>

### Finding the positional min and max

In [336]:
# Creating a new tensor for positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [337]:
# Find the arg max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [339]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [340]:
# Finding the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [344]:
# Check the equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [345]:
# Find the argmin
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [346]:
# finding the minimum using the positional arg
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor

In [353]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=(1, 1, 1, 1, 50)))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [354]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [357]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

### One Hot Encoding

In [362]:
# Create a list of indices
some_list = [0, 1, 2, 3, 0, 3]

# One hot encode the list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [365]:
# Specify custome values for one hot encoding
tf.one_hot(some_list, depth=4, on_value=2, off_value=3)

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[2, 3, 3, 3],
       [3, 2, 3, 3],
       [3, 3, 2, 3],
       [3, 3, 3, 2],
       [2, 3, 3, 3],
       [3, 3, 3, 2]], dtype=int32)>

### Few math common functions
Squaring, log and square root


In [366]:
H = tf.range(1, 10)

In [368]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [372]:
# Squaring fails when there is int dtype
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [376]:
# Find the log, will fail if int is the dtype
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and NumPy

In [380]:
# Converting an NumPy array into a tensor
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [383]:
# Converting an tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [384]:
# Converting J to NumPy array
J.numpy()

array([ 3.,  7., 10.])

In [386]:
# Default types are different
numpy_J = tf.constant(np.array([3., 4., 5.]))
tensor_J = tf.constant([3., 4., 5.])

In [388]:
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)