## Introduction to the course
* Introduction to the tensors
* Getting information from tensors
* Manupulating tensors
* Tensors and numpy
* Using @tf.function
* Using GPUs with tensorflow

## Constants

In [138]:
import tensorflow as tf

In [139]:
print(tf.__version__)

2.4.1


In [140]:
# Creating the first tensor
scalar = tf.constant(7)

In [141]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [142]:
# numebr of dimensions of the tensor
scalar.ndim

0

In [143]:
# Creating a vector
vector = tf.constant([1, 2])

In [144]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [145]:
# Checking the dimension of the vector
vector.ndim

1

In [146]:
matrix = tf.constant([[10, 7],
                    [7, 10]])

In [147]:
matrix.ndim

2

In [148]:
# create another matrix
a_matrix = tf.constant([[1., 2.],
                       [3., 4.],
                       [5., 6.]], dtype=tf.float16)

In [149]:
a_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [150]:
a_matrix.ndim

2

In [151]:
tensor = tf.constant([[[1, 2, 3],[4, 5, 6]],
                     [[7, 8, 9], [10 ,11, 12]],
                     [[13, 14, 15], [16, 17, 18]]])

In [152]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [153]:
tensor.ndim

3

## Variables

 We will create the same tensors as above

In [154]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [155]:
changable_tensor = tf.Variable([10, 5]) # Variable
unchangable_tensor = tf.constant([1, 2]) # Constant 

In [156]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5], dtype=int32)>

In [157]:
unchangable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [158]:
changable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Can be assigned to something else
changable_tensor[0].assign(7)

In [ ]:
# Now lets try to change our unchangable vector
unchangable_tensor[0].assign(7)

## Creating random tensors

Random tensors that contain arbitary values

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

In [ ]:
random_1

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [ ]:
random_2

In [ ]:
random_1 == random_2

Shuffle
* To help in training else the model will get used to it, helps in shuffle the data

In [ ]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                           [5, 6]])

In [ ]:
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
# Converting numpy arrays into tensors

In [ ]:
import numpy as np

In [ ]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_B = np.arange(1, 25, dtype=np.int32)

In [ ]:
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))

In [ ]:
A

In [ ]:
numpy_B

In [ ]:
B = tf.constant(numpy_B, shape=(3, 8))

In [ ]:
B

### Getting informationg from tensors

* Shape
* Rank
* Axis or Dimension
* Size

In [196]:
A = tf.zeros([2, 3, 4, 5])

In [197]:
A

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [198]:
A.shape

TensorShape([2, 3, 4, 5])

In [199]:
A.ndim

4

In [200]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [201]:
print("datatype: ", A.dtype)
print("the dimensions (rank): ", A.ndim)
print("Shape of the tensor: ", A.shape)
print("Elements along the 0 axis: ", A.shape[0])
print("Elements along the last axis: ", A.shape[-1])
print("Total number of elemnents in out tensor: ", tf.size(A).numpy())

datatype:  <dtype: 'float32'>
the dimensions (rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elemnents in out tensor:  120


### Indexing the tensors

In [202]:
A[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [203]:
A[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [210]:
B = tf.constant([[10, 7],
                [3, 4]])

In [211]:
B.ndim, B.shape

(2, TensorShape([2, 2]))

In [212]:
B[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [213]:
# Adding the extra dimension
C = B[..., tf.newaxis]

In [214]:
C

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [215]:
# Expand the last axis
tf.expand_dims(B, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [217]:
# Expand the first axis
tf.expand_dims(B, axis=0) 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manupulating tensors (tensor operations)

In [226]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [227]:
# This is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [230]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [231]:
# Tensor multiplication - 1
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [232]:
# Tensor multiplication - 2
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>